on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*-alpha' # Push events to matching v*, i.e. v1.0, v20.15.10

name: release parse test 5
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
        echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        echo ::set-output name=SOURCE_VER::${GITHUB_REF:11:-6}

    - name: Source naming
      run: |
        echo $SOURCE_NAME
        echo $SOURCE_BRANCH
        echo $SOURCE_TAG
        echo $SOURCE_VER
        echo $GITHUB_REF
      env:
        SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
        SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
        SOURCE_VER: ${{ steps.branch_name.outputs.SOURCE_VER }}

    - name: Checkout code
      uses: actions/checkout@master

    - name: Maven release
      uses: qcastel/github-actions-maven-release@v1.0.3
      with:
        release-branch-name: ${{ steps.branch_name.outputs.SOURCE_TAG }}

        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.HDES_GPG_KEY_ID }}
        gpg-key: ${{ secrets.HDES_GPG_KEY }}

        maven-repo-server-id: ${{ secrets.MVN_REPO_ID }}
        maven-repo-server-username: ${{ secrets.MVN_REPO_USR }}
        maven-repo-server-password: ${{ secrets.MVN_REPO_SEC }}
        maven-args: "-Phdes-release -DreleaseVersion=${{ steps.branch_name.outputs.SOURCE_VER }} -DdevelopmentVersion=999-SNAPSHOT"

        git-release-bot-name: "release-bot"
        git-release-bot-email: "olev.mutso@resys.io"

        access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
